In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('Dataset/UCI_Credit_Card.csv')

In [5]:
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [6]:
data.shape

(30000, 25)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null float64
SEX                           30000 non-null int64
EDUCATION                     30000 non-null int64
MARRIAGE                      30000 non-null int64
AGE                           30000 non-null int64
PAY_0                         30000 non-null int64
PAY_2                         30000 non-null int64
PAY_3                         30000 non-null int64
PAY_4                         30000 non-null int64
PAY_5                         30000 non-null int64
PAY_6                         30000 non-null int64
BILL_AMT1                     30000 non-null float64
BILL_AMT2                     30000 non-null float64
BILL_AMT3                     30000 non-null float64
BILL_AMT4                     30000 non-null float64
BILL_AMT5                     30000 non-null float64
BILL_AMT6                     30000 non-null float64
PAY_AMT1                      30000 non-null float64
PAY_AMT2                      30000 non-null float64
PAY_AMT3                      30000 non-null float64
PAY_AMT4                      30000 non-null float64
PAY_AMT5                      30000 non-null float64
PAY_AMT6                      30000 non-null float64
default.payment.next.month    30000 non-null int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [10]:
data.isnull().values.any()

False

In [11]:
data['SEX'].value_counts()

2    18112
1    11888
Name: SEX, dtype: int64

In [12]:
data.apply(lambda x: sum(x.isnull()),axis=0)

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [13]:
features=data.drop(['ID'],axis=1)

In [14]:
features.rename(columns={'default.payment.next.month':'DEFAULT'},inplace=True)

In [15]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
LIMIT_BAL    30000 non-null float64
SEX          30000 non-null int64
EDUCATION    30000 non-null int64
MARRIAGE     30000 non-null int64
AGE          30000 non-null int64
PAY_0        30000 non-null int64
PAY_2        30000 non-null int64
PAY_3        30000 non-null int64
PAY_4        30000 non-null int64
PAY_5        30000 non-null int64
PAY_6        30000 non-null int64
BILL_AMT1    30000 non-null float64
BILL_AMT2    30000 non-null float64
BILL_AMT3    30000 non-null float64
BILL_AMT4    30000 non-null float64
BILL_AMT5    30000 non-null float64
BILL_AMT6    30000 non-null float64
PAY_AMT1     30000 non-null float64
PAY_AMT2     30000 non-null float64
PAY_AMT3     30000 non-null float64
PAY_AMT4     30000 non-null float64
PAY_AMT5     30000 non-null float64
PAY_AMT6     30000 non-null float64
DEFAULT      30000 non-null int64
dtypes: float64(13), int64(11)
memory usage: 5.5 MB

In [16]:
label_data=features['DEFAULT']

In [17]:
##label_data=pd.get_dummies(label_data)

In [18]:
features.drop(['DEFAULT'],axis=1)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,2,2,2,26,-1,2,0,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,2,2,2,34,0,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,2,2,1,37,0,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
5,50000.0,1,1,2,37,0,0,0,0,0,...,57608.0,19394.0,19619.0,20024.0,2500.0,1815.0,657.0,1000.0,1000.0,800.0
6,500000.0,1,1,2,29,0,0,0,0,0,...,445007.0,542653.0,483003.0,473944.0,55000.0,40000.0,38000.0,20239.0,13750.0,13770.0
7,100000.0,2,2,2,23,0,-1,-1,0,0,...,601.0,221.0,-159.0,567.0,380.0,601.0,0.0,581.0,1687.0,1542.0
8,140000.0,2,3,1,28,0,0,2,0,0,...,12108.0,12211.0,11793.0,3719.0,3329.0,0.0,432.0,1000.0,1000.0,1000.0
9,20000.0,1,3,2,35,-2,-2,-2,-2,-1,...,0.0,0.0,13007.0,13912.0,0.0,0.0,0.0,13007.0,1122.0,0.0
10,200000.0,2,3,2,34,0,0,2,0,0,...,5535.0,2513.0,1828.0,3731.0,2306.0,12.0,50.0,300.0,3738.0,66.0
11,260000.0,2,1,2,51,-1,-1,-1,-1,-1,...,9966.0,8517.0,22287.0,13668.0,21818.0,9966.0,8583.0,22301.0,0.0,3640.0
12,630000.0,2,2,2,41,-1,0,-1,-1,-1,...,6500.0,6500.0,6500.0,2870.0,1000.0,6500.0,6500.0,6500.0,2870.0,0.0
13,70000.0,1,2,2,30,1,2,2,0,0,...,65701.0,66782.0,36137.0,36894.0,3200.0,0.0,3000.0,3000.0,1500.0,0.0
14,250000.0,1,1,2,29,0,0,0,0,0,...,63561.0,59696.0,56875.0,55512.0,3000.0,3000.0,3000.0,3000.0,3000.0,3000.0
15,50000.0,2,3,3,23,1,2,0,0,0,...,28116.0,28771.0,29531.0,30211.0,0.0,1500.0,1100.0,1200.0,1300.0,1100.0
16,20000.0,1,1,2,24,0,0,2,2,2,...,17428.0,18338.0,17905.0,19104.0,3200.0,0.0,1500.0,0.0,1650.0,0.0
17,320000.0,1,1,1,49,0,0,0,-1,-1,...,194663.0,70074.0,5856.0,195599.0,10358.0,10000.0,75940.0,20000.0,195599.0,50000.0
18,360000.0,2,1,1,49,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,180000.0,2,1,2,29,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,130000.0,2,3,2,39,0,0,0,0,0,...,24489.0,20616.0,11802.0,930.0,3000.0,1537.0,1000.0,2000.0,930.0,33764.0
21,120000.0,2,2,1,39,-1,-1,-1,-1,-1,...,316.0,0.0,632.0,316.0,316.0,316.0,0.0,632.0,316.0,0.0
22,70000.0,2,2,2,26,2,0,0,2,2,...,45020.0,44006.0,46905.0,46012.0,2007.0,3582.0,0.0,3601.0,0.0,1820.0
23,450000.0,2,1,1,40,-2,-2,-2,-2,-2,...,1473.0,560.0,0.0,0.0,19428.0,1473.0,560.0,0.0,0.0,1128.0
24,90000.0,1,1,2,23,0,0,0,-1,0,...,0.0,5398.0,6360.0,8292.0,5757.0,0.0,5398.0,1200.0,2045.0,2000.0
25,50000.0,1,3,2,23,0,0,0,0,0,...,36023.0,28967.0,29829.0,30046.0,1973.0,1426.0,1001.0,1432.0,1062.0,997.0
26,60000.0,1,1,2,27,1,-2,-1,-1,-1,...,259.0,-57.0,127.0,-189.0,0.0,1000.0,0.0,500.0,0.0,1000.0
27,50000.0,2,3,2,30,0,0,0,0,0,...,17163.0,17878.0,18931.0,19617.0,1300.0,1300.0,1000.0,1500.0,1000.0,1012.0
28,50000.0,2,3,1,47,-1,-1,-1,-1,-1,...,3416.0,2040.0,30430.0,257.0,3415.0,3421.0,2044.0,30430.0,257.0,0.0
29,50000.0,1,1,2,26,0,0,0,0,0,...,17496.0,17907.0,18375.0,11400.0,1500.0,1500.0,1000.0,1000.0,1600.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29970,360000.0,1,1,1,34,-1,-1,-1,0,0,...,64069.0,49005.0,8676.0,19487.0,52951.0,64535.0,8907.0,53.0,19584.0,16080.0
29971,80000.0,1,3,1,36,0,0,0,0,0,...,68279.0,69674.0,71070.0,73612.0,2395.0,2500.0,2530.0,2556.0,3700.0,3000.0
29972,190000.0,1,1,1,37,0,0,0,0,0,...,5869.0,29223.0,19616.0,148482.0,2000.0,3869.0,25128.0,10115.0,148482.0,4800.0
29973,230000.0,1,2,1,35,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29974,50000.0,1,2,1,37,1,2,2,2,0,...,4328.0,2846.0,1585.0,1324.0,0.0,3000.0,0.0,0.0,1000.0,1000.0
29975,220000.0,1,2,1,41,0,0,-1,-1,-2,...,1369.0,5924.0,1759.0,1824.0,8840.0,6643.0,5924.0,1759.0,1824.0,7022.0
29976,40000.0,1,2,2,47,2,2,3,2,2,...,53415.0,51259.0,47151.0,46934.0,4000.0,0.0,2000.0,0.0,3520.0,0.0
29977,420000.0,1,1,2,34,0,0,0,0,0,...,140011.0,141695.0,144839.0,147954.0,7000.0,7000.0,5500.0,5500.0,5600.0,5000.0
29978,310000.0,1,2,1,39,0,0,0,0,0,...,233854.0,219409.0,216540.0,210675.0,10029.0,9218.0,10029.0,8049.0,8040.0,10059.0
29979,180000.0,1,1,1,32,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29980,50000.0,1,3,2,42,0,0,0,0,0,...,49397.0,50360.0,19971.0,19694.0,10000.0,4000.0,5000.0,3000.0,4500.0,2000.0
29981,50000.0,1,2,1,44,1,2,2,2,0,...,33101.0,28192.0,22676.0,14647.0,2300.0,1700.0,0.0,517.0,503.0,585.0
29982,90000.0,1,2,1,36,0,0,0,0,0,...,10306.0,11328.0,12036.0,14329.0,1500.0,1500.0,1500.0,1200.0,2500.0,0.0
29983,20000.0,1,2,1,44,-2,-2,-2,-2,-2,...,2712.0,2882.0,9235.0,1719.0,2890.0,2720.0,2890.0,9263.0,1824.0,1701.0
29984,30000.0,1,2,2,38,-1,-1,-2,-1,-1,...,2939.0,1993.0,1907.0,3319.0,923.0,2977.0,1999.0,3057.0,3319.0,1000.0
29985,240000.0,1,1,2,30,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29986,360000.0,1,1,2,35,-1,-1,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29987,130000.0,1,1,2,34,0,0,0,0,0,...,15546.0,108047.0,93708.0,97353.0,3000.0,2000.0,93000.0,4000.0,5027.0,4005.0
29988,250000.0,1,1,1,34,0,0,0,0,0,...,243075.0,245750.0,175005.0,179687.0,65000.0,8800.0,9011.0,6000.0,7000.0,6009.0
29989,150000.0,1,1,2,35,-1,-1,-1,-1,-1,...,-3.0,780.0,0.0,0.0,9054.0,0.0,783.0,0.0,0.0,0.0
29990,140000.0,1,2,1,41,0,0,0,0,0,...,139110.0,138262.0,49675.0,46121.0,6000.0,7000.0,4228.0,1505.0,2000.0,2000.0
29991,210000.0,1,2,1,34,3,2,2,2,2,...,2500.0,2500.0,2500.0,2500.0,0.0,0.0,0.0,0.0,0.0,0.0
29992,10000.0,1,3,1,43,0,0,0,-2,-2,...,0.0,0.0,0.0,0.0,2000.0,0.0,0.0,0.0,0.0,0.0
29993,100000.0,1,1,2,38,0,-1,-1,0,0,...,102996.0,70626.0,69473.0,55004.0,2000.0,111784.0,4000.0,3000.0,2000.0,2000.0
29994,80000.0,1,2,2,34,2,2,2,2,2,...,79384.0,77519.0,82607.0,81158.0,7000.0,3500.0,0.0,7000.0,0.0,4000.0
29995,220000.0,1,3,1,39,0,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,3,2,43,-1,-1,-1,-1,0,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,2,2,37,4,3,2,-1,0,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,3,1,41,1,-1,0,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,50000.0,1,2,1,46,0,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [19]:
from sklearn.model_selection import train_test_split # very handy way of selecting sets

In [20]:
# Train Test Split
# Training Data = 80% of Dataset
# Test Data = 20% of Dataset


x_train,x_test,y_train,y_test=train_test_split(features,label_data,test_size=0.2,random_state=1,stratify=label_data)

In [21]:
x_train.shape

(24000, 24)

In [22]:
y_train.shape

(24000,)

In [23]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24000, 24)
(6000, 24)
(24000,)
(6000,)

In [24]:
#Logistic regression

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [26]:
yr=LR.predict(x_test)

In [27]:
yr

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
yr_prob=LR.predict_proba(x_test)

In [29]:
yr_prob

array([[0.75805684, 0.24194316],
       [0.65363449, 0.34636551],
       [0.78289365, 0.21710635],
       ...,
       [0.82997439, 0.17002561],
       [0.75077425, 0.24922575],
       [0.99556647, 0.00443353]])

In [30]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yr)

0.7785

In [31]:
#Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
RF=RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0).fit(x_train,y_train)

In [34]:
RF

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [35]:
Rr=RF.predict(x_test)

In [36]:
Rr

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, Rr)

0.8781666666666667

In [38]:
#SVM

In [39]:
from sklearn.svm import SVC

In [40]:
svc=SVC(gamma='auto').fit(x_train,y_train)

In [41]:
svc

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
sr=svc.predict(x_test)

In [43]:
sr

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, sr)

0.7796666666666666

In [45]:
#Neural Network

In [46]:
label_data=pd.get_dummies(label_data)

In [49]:
x_train1,x_test1,y_train1,y_test1=train_test_split(features,label_data,test_size=0.2,random_state=1,stratify=label_data)

In [50]:
x_train1.shape

(24000, 24)

In [51]:
y_train1.shape

(24000, 2)

In [52]:
y_train.head()

10029    0
17540    1
20357    1
20217    0
17264    1
Name: DEFAULT, dtype: int64

In [54]:
m,n=x_train1.shape
print(m)
print(n)

24000
24

In [56]:
import tensorflow as tf

In [108]:
learning_rate = 0.01
training_epochs = 15

tf.reset_default_graph()

# By aving 2 features: hours slept & hours studied
X = tf.placeholder(tf.float32, [None, n], name="X")
Y = tf.placeholder(tf.float32, [None, 2], name="Y")

In [109]:
# Initialize our weigts & bias
W = tf.get_variable("W", [n, 2], initializer = tf.contrib.layers.xavier_initializer())
b = tf.get_variable("b", [2], initializer = tf.zeros_initializer())
print(W.shape)

(24, 2)

In [110]:
Z = tf.add(tf.matmul(X, W), b)
prediction = tf.nn.sigmoid(Z)

In [111]:
cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = Z, labels = Y))

In [112]:
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [113]:
init = tf.global_variables_initializer()

cost_history = np.empty(shape=[1],dtype=float)

In [114]:
with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(training_epochs):
        _, c = sess.run([optimizer, cost], feed_dict={X: x_train1, Y: y_train1})
        print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(c), \
               "W=", sess.run(W), "b=", sess.run(b))
        cost_history = np.append(cost_history, c)
        
        
    # Calculate the correct predictions
    correct_prediction = tf.to_float(tf.greater(prediction, 0.5))

    # Calculate accuracy on the test set
    accuracy = tf.reduce_mean(tf.to_float(tf.equal(Y, correct_prediction)))
    print ("Accuracy:", accuracy.eval({X:x_train1, Y:y_train1}))
    print ("test Accuracy:", accuracy.eval({X:x_test1, Y:y_test1}))

Epoch: 0001 cost= 30966.656250000 W= [[ 0.08903158  0.420673  ]
 [ 0.05391096  0.34374774]
 [-0.17926933 -0.23727226]
 [-0.1615858   0.42520583]
 [-0.30155578  0.22691433]
 [-0.08525252 -0.05901212]
 [ 0.05927492  0.18290327]
 [ 0.01990187  0.29746446]
 [-0.17874925  0.06938319]
 [-0.22042252 -0.43155414]
 [ 0.32402575  0.09164577]
 [ 0.02140961  0.27530938]
 [-0.36234108  0.3128795 ]
 [ 0.4698807  -0.3575861 ]
 [-0.43614462  0.11005055]
 [-0.03543463 -0.11060096]
 [ 0.3258266  -0.43532762]
 [-0.4662194  -0.1821119 ]
 [ 0.44152635 -0.14007147]
 [ 0.45876944 -0.2857942 ]
 [-0.36612615  0.11817043]
 [ 0.01883606  0.3220139 ]
 [-0.03570204 -0.03039403]
 [-0.15819848  0.35377714]] b= [ 0.00999961 -0.00999999]
Epoch: 0002 cost= 29053.951171875 W= [[ 0.08186226  0.41067368]
 [ 0.04772941  0.33374864]
 [-0.18402988 -0.24727122]
 [-0.16676128  0.41520688]
 [-0.3081247   0.21691528]
 [-0.09516079 -0.04901285]
 [ 0.04957914  0.1929028 ]
 [ 0.01285775  0.3074646 ]
 [-0.18842976  0.07938364]
 [-0.23030205 -0.42155373]
 [ 0.31419414  0.10164654]
 [ 0.02770133  0.2653099 ]
 [-0.3552419   0.30288061]
 [ 0.4749268  -0.36758447]
 [-0.43087173  0.10005254]
 [-0.0322322  -0.12059893]
 [ 0.32560855 -0.44532555]
 [-0.4565038  -0.19210553]
 [ 0.4419471  -0.15006731]
 [ 0.46378878 -0.2957891 ]
 [-0.35697278  0.10817255]
 [ 0.01936165  0.3120149 ]
 [-0.02697224 -0.04039314]
 [-0.16821027  0.36375636]] b= [ 0.00391789 -0.01999899]
Epoch: 0003 cost= 27161.978515625 W= [[ 0.07340623  0.40067628]
 [ 0.03977679  0.32375273]
 [-0.19124465 -0.2572666 ]
 [-0.17419107  0.4052116 ]
 [-0.31627673  0.20691952]
 [-0.10513227 -0.03901123]
 [ 0.03974225  0.20290205]
 [ 0.00446459  0.31746668]
 [-0.19825394  0.08938809]
 [-0.24025454 -0.4115496 ]
 [ 0.30427212  0.11165189]
 [ 0.03118905  0.25531343]
 [-0.35026485  0.29288542]
 [ 0.47639945 -0.37757722]
 [-0.4290043   0.09006076]
 [-0.03313963 -0.13059016]
 [ 0.32136816 -0.45531633]
 [-0.44687617 -0.20208731]
 [ 0.43812346 -0.16004783]
 [ 0.46522138 -0.30577093]
 [-0.3481968   0.09818051]
 [ 0.01570718  0.30202064]
 [-0.01924899 -0.05038866]
 [-0.17824     0.3734493 ]] b= [-0.00398465 -0.02999452]
Epoch: 0004 cost= 25259.328125000 W= [[ 0.06439292  0.39068273]
 [ 0.03108871  0.31376618]
 [-0.19944    -0.26725075]
 [-0.18253002  0.39522693]
 [-0.32509774  0.1969333 ]
 [-0.11515111 -0.02899485]
 [ 0.02980898  0.21290897]
 [-0.00452764  0.32748005]
 [-0.20818001  0.09940654]
 [-0.25026467 -0.4015316 ]
 [ 0.2942811   0.12167086]
 [ 0.03293952  0.2453243 ]
 [-0.34657255  0.28289917]
 [ 0.4756995  -0.38755792]
 [-0.42923573  0.08008243]
 [-0.03629143 -0.14056686]
 [ 0.3153132  -0.46529222]
 [-0.43724364 -0.21204893]
 [ 0.43243763 -0.1700002 ]
 [ 0.4646398  -0.31573024]
 [-0.33946934  0.08819752]
 [ 0.01018279  0.29203376]
 [-0.01191313 -0.0603756 ]
 [-0.1882804   0.38206154]] b= [-0.01263986 -0.03998005]
Epoch: 0005 cost= 23409.582031250 W= [[ 0.05513422  0.3807069 ]
 [ 0.02206819  0.30382308]
 [-0.2080754  -0.27718583]
 [-0.19127487  0.38528857]
 [-0.33422253  0.18699008]
 [-0.125198   -0.01892538]
 [ 0.01981536  0.22296046]
 [-0.01383655  0.3375394 ]
 [-0.21817316  0.10946846]
 [-0.26031637 -0.39147392]
 [ 0.28423953  0.1317288 ]
 [ 0.0339435   0.23538984]
 [-0.34331575  0.27297416]
 [ 0.47391576 -0.39746678]
 [-0.43050638  0.07018434]
 [-0.040591   -0.15045471]
 [ 0.30834886 -0.47517505]
 [-0.4275529  -0.22195858]
 [ 0.42592326 -0.17988265]
 [ 0.46322975 -0.32563725]
 [-0.33059824  0.07824596]
 [ 0.00378921  0.28207448]
 [-0.00456946 -0.07032759]
 [-0.19832116  0.38967735]] b= [-0.02163483 -0.04992081]
Epoch: 0006 cost= 21773.619140625 W= [[ 0.04590261  0.37076646]
 [ 0.01302572  0.29395342]
 [-0.21675746 -0.28703746]
 [-0.20005383  0.37542826]
 [-0.34336802  0.17712036]
 [-0.13525265 -0.00879989]
 [ 0.00979315  0.23307367]
 [-0.02327727  0.34765726]
 [-0.22820403  0.11958276]
 [-0.27040112 -0.38136774]
 [ 0.27415654  0.1418346 ]
 [ 0.03522019  0.22558016]
 [-0.33962083  0.2631867 ]
 [ 0.47207892 -0.40721628]
 [-0.43176836  0.06046504]
 [-0.0451517  -0.16014235]
 [ 0.30106342 -0.4848482 ]
 [-0.41776612 -0.23178244]
 [ 0.41931924 -0.1896569 ]
 [ 0.46220875 -0.3354577 ]
 [-0.32144475  0.06836432]
 [-0.00266513  0.27216807]
 [ 0.00315481 -0.08021642]
 [-0.20835069  0.3975915 ]] b= [-0.03065649 -0.05978572]
Epoch: 0007 cost= 20344.720703125 W= [[ 3.7039720e-02  3.6087918e-01]
 [ 4.3151425e-03  2.8417715e-01]
 [-2.2504927e-01 -2.9678485e-01]
 [-2.0844975e-01  3.6566612e-01]
 [-3.5220772e-01  1.6734444e-01]
 [-1.4528996e-01  1.3892008e-03]
 [-2.1891575e-04  2.4325146e-01]
 [-3.2645565e-02  3.5783568e-01]
 [-2.3824137e-01  1.2975085e-01]
 [-2.8049546e-01 -3.7121224e-01]
 [ 2.6406798e-01  1.5198974e-01]
 [ 3.7749652e-02  2.1597303e-01]
 [-3.3478996e-01  2.5362191e-01]
 [ 4.7131488e-01 -4.1670895e-01]
 [-4.3187428e-01  5.1031340e-02]
 [-4.8954915e-02 -1.6951443e-01]
 [ 2.9408559e-01 -4.9419141e-01]
 [-4.0786821e-01 -2.4148911e-01]
 [ 4.1350600e-01 -1.9928713e-01]
 [ 4.6290684e-01 -3.4514862e-01]
 [-3.1200659e-01  5.8596529e-02]
 [-8.2478402e-03  2.6234025e-01]
 [ 1.1422418e-02 -9.0012744e-02]
 [-2.1835859e-01  4.0597260e-01]] b= [-0.03934409 -0.06955492]
Epoch: 0008 cost= 19136.939453125 W= [[ 0.02896859  0.35106033]
 [-0.00367733  0.27451545]
 [-0.23250102 -0.3064033 ]
 [-0.21599613  0.3560245 ]
 [-0.36038104  0.1576842 ]
 [-0.1552893   0.01164851]
 [-0.0101918   0.25349447]
 [-0.04176993  0.36807564]
 [-0.24826199  0.13997157]
 [-0.29058525 -0.36100942]
 [ 0.2539774   0.16219278]
 [ 0.04187375  0.20664379]
 [-0.3287208   0.24436267]
 [ 0.47229943 -0.42585167]
 [-0.43019953  0.04198097]
 [-0.05118759 -0.17846613]
 [ 0.28797942 -0.5030951 ]
 [-0.39785928 -0.25104806]
 [ 0.40925592 -0.20874834]
 [ 0.465764   -0.35468653]
 [-0.30232516  0.04897326]
 [-0.01206887  0.2526141 ]
 [ 0.0201651  -0.0997031 ]
 [-0.22833383  0.4147874 ]] b= [-0.0473035  -0.07920644]
Epoch: 0009 cost= 18097.248046875 W= [[ 0.021938    0.341322  ]
 [-0.01076297  0.26498646]
 [-0.23889837 -0.31587157]
 [-0.22247237  0.3465227 ]
 [-0.36772597  0.14815892]
 [-0.16526675  0.02198085]
 [-0.0201521   0.26380172]
 [-0.05069719  0.37837523]
 [-0.25830188  0.15024257]
 [-0.3007099  -0.35076293]
 [ 0.24385166  0.17243977]
 [ 0.04728375  0.19765559]
 [-0.32170004  0.23547795]
 [ 0.474859   -0.434567  ]
 [-0.42696214  0.03339453]
 [-0.05179717 -0.18691467]
 [ 0.28285405 -0.51147664]
 [-0.38775158 -0.26043862]
 [ 0.40669015 -0.21801819]
 [ 0.47037846 -0.3640461 ]
 [-0.29243955  0.0395243 ]
 [-0.01400487  0.24300458]
 [ 0.02928355 -0.10926749]
 [-0.23827608  0.42397586]] b= [-0.05434753 -0.08872136]
Epoch: 0010 cost= 17189.599609375 W= [[ 0.01590397  0.3316718 ]
 [-0.01709524  0.25560418]
 [-0.24445404 -0.3251714 ]
 [-0.22805262  0.33717358]
 [-0.3744019   0.13878332]
 [-0.17527108  0.03238601]
 [-0.03017291  0.27417225]
 [-0.0596873   0.38873214]
 [-0.2684323   0.16056189]
 [-0.31092358 -0.34047478]
 [ 0.23363383  0.18272755]
 [ 0.05346442  0.18904977]
 [-0.3140952   0.22701494]
 [ 0.4783285  -0.44280362]
 [-0.42280644  0.02532586]
 [-0.05144557 -0.19480582]
 [ 0.27822125 -0.5192844 ]
 [-0.37756592 -0.26965007]
 [ 0.40532523 -0.22708566]
 [ 0.47616267 -0.37321138]
 [-0.2823847   0.03026221]
 [-0.01449971  0.23352708]
 [ 0.03863929 -0.11869267]
 [-0.24819864  0.43348563]] b= [-0.06064304 -0.09808493]
Epoch: 0011 cost= 16393.439453125 W= [[ 0.01059396  0.32211322]
 [-0.02301617  0.24637617]
 [-0.24958302 -0.33429363]
 [-0.23313262  0.3279842 ]
 [-0.38072008  0.12956564]
 [-0.18534458  0.04286047]
 [-0.04030152  0.2846012 ]
 [-0.06894027  0.39914128]
 [-0.2786885   0.17092448]
 [-0.32125163 -0.33014947]
 [ 0.22329867  0.19305168]
 [ 0.05984741  0.1808528 ]
 [-0.3063132   0.21900246]
 [ 0.48189652 -0.4505304 ]
 [-0.4184864   0.01780481]
 [-0.05099409 -0.20211388]
 [ 0.2734099  -0.52649546]
 [-0.36733142 -0.27867863]
 [ 0.40446204 -0.23594676]
 [ 0.48265135 -0.38216797]
 [-0.27220002  0.02119531]
 [-0.01418664  0.22419427]
 [ 0.04807862 -0.12797454]
 [-0.25811628  0.44327506]] b= [-0.06653725 -0.10728965]
Epoch: 0012 cost= 15702.807617188 W= [[ 0.00591596  0.312652  ]
 [-0.02872462  0.23731287]
 [-0.25457963 -0.34322184]
 [-0.23794962  0.31896806]
 [-0.38687596  0.1205192 ]
 [-0.19551446  0.05339989]
 [-0.0505675   0.2950846 ]
 [-0.07852204  0.40959817]
 [-0.28908426  0.18132517]
 [-0.33170494 -0.31979257]
 [ 0.2128377   0.20340644]
 [ 0.06587423  0.17309704]
 [-0.29875433  0.2114751 ]
 [ 0.4848185  -0.45770937]
 [-0.41469783  0.01086629]
 [-0.0511451  -0.20881326]
 [ 0.26798105 -0.53308463]
 [-0.3570726  -0.28751588]
 [ 0.4035009  -0.2445879 ]
 [ 0.48944178 -0.39090186]
 [-0.26191437  0.01233504]
 [-0.013747    0.21502134]
 [ 0.05746624 -0.137111  ]
 [-0.26804003  0.45330757]] b= [-0.07224258 -0.1163225 ]
Epoch: 0013 cost= 15102.956054688 W= [[ 0.00204138  0.30329216]
 [-0.03425996  0.22842492]
 [-0.2595454  -0.35194308]
 [-0.24256785  0.31013748]
 [-0.39290944  0.11165486]
 [-0.20579652  0.06400057]
 [-0.06098095  0.3056205 ]
 [-0.08841261  0.42010033]
 [-0.29962176  0.19176126]
 [-0.34228846 -0.3094083 ]
 [ 0.2022481   0.21378762]
 [ 0.07123633  0.1658054 ]
 [-0.29164362  0.20445895]
 [ 0.4867102  -0.46431372]
 [-0.411813    0.00453069]
 [-0.05219353 -0.21488759]
 [ 0.26184022 -0.5390398 ]
 [-0.34680697 -0.29615316]
 [ 0.40218943 -0.25300154]
 [ 0.49627873 -0.39941534]
 [-0.25154975  0.00368921]
 [-0.01341441  0.20602453]
 [ 0.06671939 -0.14609699]
 [-0.27797598  0.46355373]] b= [-0.07781138 -0.12517232]
Epoch: 0014 cost= 14571.425781250 W= [[-4.65204706e-04  2.94034064e-01]
 [-3.94034944e-02  2.19714090e-01]
 [-2.64308751e-01 -3.60454381e-01]
 [-2.46778622e-01  3.01494956e-01]
 [-3.98619711e-01  1.02974832e-01]
 [-2.16203704e-01  7.46568590e-02]
 [-7.15502948e-02  3.16204727e-01]
 [-9.85719487e-02  4.30643439e-01]
 [-3.10298741e-01  2.02227429e-01]
 [-3.53002131e-01 -2.98999965e-01]
 [ 1.91529423e-01  2.24191427e-01]
 [ 7.57384151e-02  1.58984169e-01]
 [-2.85124302e-01  1.97961032e-01]
 [ 4.87393111e-01 -4.70339745e-01]
 [-4.10020828e-01 -1.20135816e-03]
 [-5.42359762e-02 -2.20339298e-01]
 [ 2.55014688e-01 -5.44364810e-01]
 [-3.36541265e-01 -3.04592729e-01]
 [ 4.00349736e-01 -2.61191159e-01]
 [ 5.03093362e-01 -4.07700241e-01]
 [-2.41121903e-01 -4.73580323e-03]
 [-1.31966425e-02  1.97225019e-01]
 [ 7.58032203e-02 -1.54930711e-01]
 [-2.87917763e-01  4.73988086e-01]] b= [-0.08303507 -0.13383722]
Epoch: 0015 cost= 14091.993164062 W= [[ 2.38295936e-04  2.84879535e-01]
 [-4.28031683e-02  2.11179987e-01]
 [-2.67639130e-01 -3.68755102e-01]
 [-2.49192670e-01  2.93040037e-01]
 [-4.02671367e-01  9.44794863e-02]
 [-2.26755381e-01  8.53626281e-02]
 [-8.22227150e-02  3.26831162e-01]
 [-1.08688325e-01  4.41221654e-01]
 [-3.20944369e-01  2.12719798e-01]
 [-3.63671094e-01 -2.88571596e-01]
 [ 1.80862978e-01  2.34613448e-01]
 [ 7.93104991e-02  1.52641237e-01]
 [-2.79247463e-01  1.91987514e-01]
 [ 4.86877918e-01 -4.75782305e-01]
 [-4.09332842e-01 -6.32919604e-03]
 [-5.72254136e-02 -2.25171775e-01]
 [ 2.47594282e-01 -5.49066544e-01]
 [-3.26278955e-01 -3.12825441e-01]
 [ 3.97955537e-01 -2.69149631e-01]
 [ 5.09888530e-01 -4.15753752e-01]
 [-2.30641097e-01 -1.29321897e-02]
 [-1.30411657e-02  1.88631848e-01]
 [ 8.46849009e-02 -1.63603067e-01]
 [-2.97806233e-01  4.84588861e-01]] b= [-0.08656407 -0.14231706]
Accuracy: 0.5413542
test Accuracy: 0.54216665